### ISSUE TITLE
Catering Menu Accessibility 

### ISSUE THREAD

**Issue by derekober** [hhgr/HeritageLancaster#1]
Our catering menu appears to be fairly difficult to locate at HeritageLancaster.com 
There is a small "call-out" box on the right side of http://www.heritagelancaster.com/meetings 
Could we add something similar to this page?: http://www.heritagelancaster.com/lancaster-event-catering-banquets or perhaps somewhere in the body of the page? If you have any additional thoughts feel free to share. Thanks, Adam!

**Comment by AdamChlan** [comment]
@derekober Would you like the audio/video and room spec links to appear on this page as well?

**Comment by derekober** [comment]
Yes, I think that would be a great addition!

**Comment by AdamChlan** [comment]
@derekober okay, this has been added to the sidebar. would it make sense to link up "all-inclusive package menus." in the body copy?

**Comment by derekober** [comment]
@AdamChlan  Is this something on the other page as well? I believe I want to say yes to that. I trust your judgement on this!

**Comment by AdamChlan** [comment]
@derekober The meeting page has no link in the body. I have added one to this page:

http://www.heritagelancaster.com/lancaster-event-catering-banquets

...as well as the box on the right with the links.
