### ISSUE TITLE
Heritage Lancaster Homepage Announcements

### ISSUE THREAD

**Issue by derekober** [hhgr/HeritageLancaster#3]
Adam,

When attempting to update the Heritage Lancaster homepage announcements, I encounter this error while trying to upload a new file/image to use:

![error msg](https://cloud.githubusercontent.com/assets/15049304/12353440/49f6b7bc-bb5d-11e5-978a-a81b2fdc0fbe.PNG)

Is this due to the wrong dimensions for an image to be used there?

**Comment by AdamChlan** [comment]
No this is because of the new server the site is on. I will take a look this morning.

**Comment by AdamChlan** [comment]
Derek, give this another shot. If you try to upload images to other areas of the site, you will likely get this message. I am going to be moving the sites again in the very near future, but let me know if you run into this again over the next few days.

Adam

**Comment by derekober** [comment]
No issues this time around. Thank you, Adam!
